### ISSUE TITLE
因 API 使用错误导致的增加中心服务器压力

### ISSUE THREAD

**Issue by bytfr** [SaltWood-Studio/CSharp-OpenBMCLAPI#4]
在大量补全文件时(即第一次使用)，使用了**错误的接口**(/openbmclapi/download/{hash})，应该使用https://bmclapi2.bangbang93.com/{path}。
如果使用本接口进行大量下载时**会被ban**。建议立即修复

**Comment by SALTWOOD** [comment]
了解。周六修复

**Comment by SALTWOOD** [comment]
已修复完成，critical 类别 issue 修复后将会立即合并至 master
