### ISSUE TITLE
SSL删除证书错误

### ISSUE THREAD

**Issue by kndxhz** [SaltWood-Studio/CSharp-OpenBMCLAPI#5]
源码来自dev分支
### 1. **概率触发**的删除证书错误（文件被锁定？）
![822041d7d5acb26260c2e48b437a915c](https://github.com/SaltWood-Studio/CSharp-OpenBMCLAPI/assets/113306265/442d0f73-f13b-4f78-8d26-d79519e21f58)
![c8b6a846515c1e39688625c3a5d0c085](https://github.com/SaltWood-Studio/CSharp-OpenBMCLAPI/assets/113306265/db80b0e6-036c-4392-983a-ee551fd20771)

**Comment by SALTWOOD** [comment]
已修复，`File.Delete()` 语句为多余，因为 `File.Create()` 会覆盖文件内容。
